[package]
name = "organizer"
version = "0.1.0"
authors = ["Thomas Fasan"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "=0.1.5"
js-sys = "0.3.19"
cgmath = "0.18.0"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2.44"
gloo-render = "0.1.1"
gloo-events = "0.1.2"
gloo-utils = "0.1.7"
gloo-console = "0.2.3"

#texture batching
guillotiere = "0.6.2"

[dependencies.web-sys]
version = "0.3.4"
features = [
    'Document',
    'Element',
    'EventTarget',
    'HtmlCanvasElement',
    'HtmlImageElement',
    'HtmlVideoElement',
    'KeyboardEvent',
    'FocusEvent',
    'MouseEvent',
    'WebGlBuffer',
    'WebGlVertexArrayObject',
    'WebGlProgram',
    'WebGl2RenderingContext',
    'WebGlShader',
    'WebGlTexture',
    'WebGlUniformLocation',
    'Window',
]
